/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shsdc_shat_mms;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author panal
 */
public class addmember_form extends javax.swing.JFrame {

    LocalDateTime dt_now = LocalDateTime.now();
    DateTimeFormatter dt_now_new = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
    String formatted_dt = dt_now.format(dt_now_new);
    
    
    String curr_id_num;
    String curr_user;
    
    /**
     * Creates new form addmember_form
     */
    public addmember_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idacc_data = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        batch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_chk_id = new javax.swing.JButton();
        check_id = new javax.swing.JLabel();
        b_reg = new javax.swing.JButton();
        acc_rank = new javax.swing.JComboBox<>();
        btn_chk_username = new javax.swing.JButton();
        check_user = new javax.swing.JLabel();
        company = new javax.swing.JComboBox<>();
        rank = new javax.swing.JComboBox<>();
        designation = new javax.swing.JComboBox<>();
        status = new javax.swing.JComboBox<>();
        sc_year = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        id_log_user = new javax.swing.JLabel();
        id_log_id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Member");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        idacc_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idacc_dataActionPerformed(evt);
            }
        });
        idacc_data.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idacc_dataKeyTyped(evt);
            }
        });

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("id number");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("account rank");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("username");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("password");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("first name");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("last name");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("company");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("batch");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("rank");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("designation");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("status");

        btn_chk_id.setText("CHECK ID");
        btn_chk_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chk_idActionPerformed(evt);
            }
        });

        check_id.setForeground(new java.awt.Color(255, 255, 255));
        check_id.setText("Check ID");

        b_reg.setText("Register");
        b_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_regActionPerformed(evt);
            }
        });

        acc_rank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "admin", "member" }));
        acc_rank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acc_rankActionPerformed(evt);
            }
        });

        btn_chk_username.setText("CHECK USERNAME");
        btn_chk_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chk_usernameActionPerformed(evt);
            }
        });

        check_user.setForeground(new java.awt.Color(255, 255, 255));
        check_user.setText("Check username");

        company.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "staff", "alpha", "bravo", "charlie", "delta" }));

        rank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "colonel", "lt. colonel", "major", "captain", "1st lieutenant", "2nd lieutenant", "officer candidate", "1 AT", "2 AT", "3 AT", "4 AT", "aspirant" }));

        designation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "corps commander", "staff/Executive", "staff/Administrative", "staff/Liaison", "staff/Logistics", "staff/Safety", "staff/Intelligence", "staff/Information", "company commander", "company executive", "company guidon", "color commander", "color flag bearer", "color guard", "platoon leader", "seargent", "element" }));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "active", "inactive", "removed", "alumni" }));

        sc_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017-2018", "2018-2019", "2019-2020", "2020-2021", "2021-2022", "2022-2023", "2023-2024", "2024-2025" }));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("School Year");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Logged in as:");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("id:");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("username:");

        id_log_user.setForeground(new java.awt.Color(255, 255, 255));
        id_log_user.setText("wwww");

        id_log_id.setForeground(new java.awt.Color(255, 255, 255));
        id_log_id.setText("wwww");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(batch, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(company, javax.swing.GroupLayout.Alignment.LEADING, 0, 221, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sc_year, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(acc_rank, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idacc_data, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(designation, javax.swing.GroupLayout.Alignment.LEADING, 0, 221, Short.MAX_VALUE)
                            .addComponent(rank, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(status, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_chk_id, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_chk_username, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(check_user, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(check_id, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(id_log_id, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(id_log_user, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(b_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idacc_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btn_chk_id)
                            .addComponent(check_id))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(acc_rank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btn_chk_username)
                    .addComponent(check_user))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(company, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(batch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(b_reg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sc_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(id_log_id, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(id_log_user, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void b_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_regActionPerformed
        String curr_check_id = check_id.getText();
        String curr_check_user = check_user.getText();
        
        if(curr_check_id.equals("available") && curr_check_user.equals("available")){
            SaveData();
        }
        else{
            JOptionPane.showMessageDialog(this, "Check ID and Username", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_b_regActionPerformed

    private void acc_rankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acc_rankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acc_rankActionPerformed

    private void btn_chk_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chk_idActionPerformed
        idcheck();
    }//GEN-LAST:event_btn_chk_idActionPerformed

    private void btn_chk_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chk_usernameActionPerformed
        usercheck();
    }//GEN-LAST:event_btn_chk_usernameActionPerformed

    private void idacc_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idacc_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idacc_dataActionPerformed

    private void idacc_dataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idacc_dataKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_idacc_dataKeyTyped

    
    
    void idcheck(){
        try {
            
            boolean checking = false;
            String curr_idacc_data = idacc_data.getText();
            
            
            DBconnection.init();
            Connection c = DBconnection.getConnection();
            PreparedStatement ps = c.prepareStatement("SELECT * FROM shatdb.acc_data where idacc_data='"+idacc_data.getText()+"';");
            ResultSet rs = ps.executeQuery();
            System.out.println("going to loop");
            while (rs.next()) {
                String db_idacc_data = rs.getString("idacc_data");
                
                if (curr_idacc_data.equals(db_idacc_data)) {
                    System.out.println("set exist");
                    check_id.setText("not-available");
                    checking = true;
                    break;
                }else{
                    System.out.println("set avail");
                check_id.setText("available");
                    checking = true;
                    break;
                }
            }
            
            if (checking == false){
                System.out.println("set avail");
                check_id.setText("available");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    
    void usercheck(){
        try {
            
            
            String curr_username = username.getText();
            boolean checking = false;
            
            DBconnection.init();
            Connection c = DBconnection.getConnection();
            PreparedStatement ps = c.prepareStatement("SELECT * FROM shatdb.acc_data where username='"+username.getText()+"';");
            ResultSet rs = ps.executeQuery();
            System.out.println("going to loop");
            while (rs.next()) {
                String db_username = rs.getString("username");
                
                if (curr_username.equals(db_username)) {
                    System.out.println("set exist");
                    check_user.setText("not-available");
                    checking = true;
                }else{
                    System.out.println("set avail");
                check_user.setText("available");
                    checking = true;
                    break;
                }
            }
            
            if (checking == false){
                System.out.println("set avail");
                check_user.setText("available");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    void SaveData() {
        
        
        
        try {
            DBconnection.init();
            Connection c = DBconnection.getConnection();
            PreparedStatement ps = c.prepareStatement(
            "insert into shatdb.acc_data\n" +
"(idacc_data, acc_rank, username, password, fname, lname, company, batch, corps_rank, designation, ptstats, rifle_status, points, school_year_idschool_year)\n" +
"values\n" +
"('"
                    + idacc_data.getText()+"','"
                    + acc_rank.getSelectedItem()+"','"
                    + username.getText()+"','"
                    + password.getText()+"','"
                    + fname.getText()+"','"
                    + lname.getText()+"','"
                    + company.getSelectedItem()+"','"
                    + batch.getText()+"','"
                    + rank.getSelectedItem()+"','"
                    + designation.getSelectedItem()+"','"
                    + status.getSelectedItem()+"','"
                    + "n/a','"
                    + "0','"
                    + sc_year.getSelectedItem()+"');");
            ps.execute();
            JOptionPane.showMessageDialog(this, "Data Registered", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);
            
            log();
            idacc_data.setText("");
            username.setText("");
            password.setText("");
            fname.setText("");
            lname.setText("");
            batch.setText("");
            check_id.setText("Check ID");
            check_user.setText("Check Username");
            idacc_data.requestFocus();
            
        } catch (SQLException ex) {
            Logger.getLogger(addmember_form.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    void log() {

        try {
            DBconnection.init();
            Connection c = DBconnection.getConnection();
            PreparedStatement ps = c.prepareStatement("insert into shatdb.log(date_time, description, action_maker)values('"+formatted_dt+"', 'acc registration of"+username.getText()+"', '"+id_log_user.getText()+"');");
            ps.execute();
            //JOptionPane.showMessageDialog(this, "Data Registered", "JDB Co.", JOptionPane.INFORMATION_MESSAGE);

            

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addmember_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addmember_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addmember_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addmember_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addmember_form().setVisible(true);
            }
        });
    }
    
    
    
    
   
    
    void set_id_log_string(String id,String username){
        id_log_id.setText(id);
        id_log_user.setText(username);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> acc_rank;
    private javax.swing.JButton b_reg;
    private javax.swing.JTextField batch;
    private javax.swing.JButton btn_chk_id;
    private javax.swing.JButton btn_chk_username;
    private javax.swing.JLabel check_id;
    private javax.swing.JLabel check_user;
    private javax.swing.JComboBox<String> company;
    private javax.swing.JComboBox<String> designation;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel id_log_id;
    private javax.swing.JLabel id_log_user;
    private javax.swing.JTextField idacc_data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField password;
    private javax.swing.JComboBox<String> rank;
    private javax.swing.JComboBox<String> sc_year;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}

