/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shsdc_shat_mms;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author panal
 */
public class admin_menu extends javax.swing.JFrame {

    static LocalDateTime dt_now = LocalDateTime.now();
    static DateTimeFormatter dt_now_new = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
    static String formatted_dt = dt_now.format(dt_now_new);
   
    
    public attendance_form att_form;
    public addmember_form amform;
    public memberprofile_form memprofile_form;
    public inventory_form inven_form;
    public action_logs aclogs;

    
    /**
     * Creates new form admin_menu
     */
    public admin_menu() {
        initComponents();
        clock();
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_panel = new javax.swing.JPanel();
        addmember_button = new javax.swing.JButton();
        attendance_button = new javax.swing.JButton();
        memberprofile_button = new javax.swing.JButton();
        inventory_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id_log_id = new javax.swing.JLabel();
        id_log_user = new javax.swing.JLabel();
        time_text = new javax.swing.JLabel();
        date_text = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        logs_button = new javax.swing.JButton();
        org_logo = new javax.swing.JLabel();
        org_name_head = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SHAT MMS Admin Menu");
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 580));

        bg_panel.setBackground(new java.awt.Color(51, 51, 51));

        addmember_button.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        addmember_button.setText("ADD MEMBER");
        addmember_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmember_buttonActionPerformed(evt);
            }
        });

        attendance_button.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        attendance_button.setText("OPEN ATTENDANCE");
        attendance_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendance_buttonActionPerformed(evt);
            }
        });

        memberprofile_button.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        memberprofile_button.setText("OPEN MEMBER PROFILE");
        memberprofile_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberprofile_buttonActionPerformed(evt);
            }
        });

        inventory_button.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        inventory_button.setText("INVENTORY");
        inventory_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventory_buttonActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource_pics/shattest.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Logged in as:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("id:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("username:");

        id_log_id.setForeground(new java.awt.Color(255, 255, 255));
        id_log_id.setText("wwww");

        id_log_user.setForeground(new java.awt.Color(255, 255, 255));
        id_log_user.setText("wwww");

        time_text.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        time_text.setForeground(new java.awt.Color(255, 255, 255));
        time_text.setText("jLabel4");

        date_text.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        date_text.setForeground(new java.awt.Color(255, 255, 255));
        date_text.setText("jLabel4");

        btn_logout.setText("LOGOUT");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id_log_id, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id_log_user, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(date_text, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(time_text, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(id_log_id, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(id_log_user, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(time_text, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(date_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logs_button.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        logs_button.setText("LOGS");
        logs_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logs_buttonActionPerformed(evt);
            }
        });

        org_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource_pics/rsz_redrawed_logo_senior_high_action_team.png"))); // NOI18N

        org_name_head.setBackground(new java.awt.Color(255, 255, 255));
        org_name_head.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        org_name_head.setForeground(new java.awt.Color(255, 255, 255));
        org_name_head.setText("<html> <p align=\"center\"> SENIOR HIGH ACTION TEAM<br>\nADMIN MENU\n\n </p> </html>");

        javax.swing.GroupLayout bg_panelLayout = new javax.swing.GroupLayout(bg_panel);
        bg_panel.setLayout(bg_panelLayout);
        bg_panelLayout.setHorizontalGroup(
            bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(memberprofile_button, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inventory_button, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addmember_button, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logs_button, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attendance_button, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bg_panelLayout.createSequentialGroup()
                        .addComponent(org_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(org_name_head, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bg_panelLayout.setVerticalGroup(
            bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_panelLayout.createSequentialGroup()
                .addGroup(bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(org_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bg_panelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(org_name_head, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attendance_button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addmember_button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(memberprofile_button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inventory_button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logs_button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(bg_panelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void attendance_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendance_buttonActionPerformed
        if (att_form == null) {
            att_form = new attendance_form();
            //obj.my_update(str);
            att_form.set_id_log_string(id_log_id.getText(), id_log_user.getText());
            
            att_form.setVisible(true);
        }else {
        att_form.setVisible(true);
        }
    }//GEN-LAST:event_attendance_buttonActionPerformed

    private void addmember_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmember_buttonActionPerformed
        if (amform == null) {
            
            
            amform = new addmember_form();
                    
                    amform.set_id_log_string(id_log_id.getText(), id_log_user.getText());
            
            amform.setVisible(true);
        }else {
        amform.setVisible(true);
        }
        
    }//GEN-LAST:event_addmember_buttonActionPerformed

    private void memberprofile_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberprofile_buttonActionPerformed
        if (memprofile_form == null) {
            memprofile_form = new memberprofile_form();
            //obj.my_update(str);
            
            memprofile_form.set_id_log_string(id_log_id.getText(), id_log_user.getText());
            
            memprofile_form.setVisible(true);
        }else{
            memprofile_form.setVisible(true);
        }
    }//GEN-LAST:event_memberprofile_buttonActionPerformed

    private void inventory_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventory_buttonActionPerformed
        
        
        JOptionPane.showMessageDialog(this, "Coming SOON!!", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);
        
        
        
        /*
        if (inven_form == null) {
            inven_form = new inventory_form();
            //obj.my_update(str);
            
            inven_form.set_id_log_string(id_log_id.getText(), id_log_user.getText());
            
            inven_form.setVisible(true);
        }else{
            inven_form.setVisible(true);
        }
        */
        
        
        
    }//GEN-LAST:event_inventory_buttonActionPerformed

    private void logs_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logs_buttonActionPerformed
        if (aclogs == null) {
            aclogs = new action_logs();
            //obj.my_update(str);
            aclogs.setVisible(true);
        }else {
        aclogs.setVisible(true);
        }
    }//GEN-LAST:event_logs_buttonActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        setVisible(false);
        Login login_menu = new Login();
        login_menu.setVisible(true);
        login_menu.setResizable(false);
    }//GEN-LAST:event_btn_logoutActionPerformed

    void dt_slot() {
        boolean check = true;
        while (check == true) {
            
            
            time_text.setText(formatted_dt);
        }
    }
    
    
    public void clock()
     {
         Thread clock=new Thread()
                 {
                 public void run()
                 {
                     try {
                    while(true)
                        {
                         Calendar cal=new GregorianCalendar();
                         int day=cal.get(Calendar.DAY_OF_MONTH);
                         int month=cal.get(Calendar.MONTH)+1;
                         int year=cal.get(Calendar.YEAR);                   
                    int second=cal.get(Calendar.SECOND);
                    int minute=cal.get(Calendar.MINUTE);
                    int hour=cal.get(Calendar.HOUR);

                    time_text.setText( hour +":"+ minute +":"+ second);
                    date_text.setText( day +"-"+ month +"-"+ year );
                  //  getTime=lbltime.getText();
                   // getDate=lbldate.getText();
                                    sleep(1000);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e);


                }
            }
        };
    clock.start();
}
    
    
    void set_id_log_string(String id,String username){
        id_log_id.setText(id);
        id_log_user.setText(username);
        
    }
    
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_menu().setVisible(true);
                
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addmember_button;
    private javax.swing.JButton attendance_button;
    private javax.swing.JPanel bg_panel;
    private javax.swing.JButton btn_logout;
    private javax.swing.JLabel date_text;
    private javax.swing.JLabel id_log_id;
    private javax.swing.JLabel id_log_user;
    private javax.swing.JButton inventory_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logs_button;
    private javax.swing.JButton memberprofile_button;
    private javax.swing.JLabel org_logo;
    private javax.swing.JLabel org_name_head;
    private javax.swing.JLabel time_text;
    // End of variables declaration//GEN-END:variables
}
