/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shsdc_shat_mms;

import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author panal
 */
public class attendance_form extends javax.swing.JFrame {

    LocalDateTime dt_now = LocalDateTime.now();
    DateTimeFormatter dt_now_new = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
    String formatted_dt = dt_now.format(dt_now_new);
    DefaultTableModel Table = new DefaultTableModel();

    /**
     * Creates new form attendance_form
     */
    public attendance_form() {
        initComponents();
        Table = (DefaultTableModel) jTable1.getModel();
        clock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        date_find = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        text_username = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        text_points = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        text_status = new javax.swing.JLabel();
        text_idnumber = new javax.swing.JTextField();
        btn_findacc = new javax.swing.JButton();
        att_type = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pts_add = new javax.swing.JTextField();
        btn_enter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        text_addinfo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        att_delete_record = new javax.swing.JTextField();
        btn_delete = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        id_log_id3 = new javax.swing.JLabel();
        id_log_user3 = new javax.swing.JLabel();
        time_text3 = new javax.swing.JLabel();
        date_text3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Attendance Form");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "log_id", "Date", "Time", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("id number");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("ATTENDANCE RECORD");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Find attendance record");

        jTextField1.setText("type the date");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField1MouseExited(evt);
            }
        });

        date_find.setText("FIND");
        date_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_findActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("username");

        text_username.setForeground(new java.awt.Color(255, 255, 255));
        text_username.setText("text_username");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("POINTS");

        text_points.setForeground(new java.awt.Color(255, 255, 255));
        text_points.setText("text_points");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("status");

        text_status.setForeground(new java.awt.Color(255, 255, 255));
        text_status.setText("text_status");

        text_idnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_idnumberActionPerformed(evt);
            }
        });
        text_idnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_idnumberKeyTyped(evt);
            }
        });

        btn_findacc.setText("Find Account");
        btn_findacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findaccActionPerformed(evt);
            }
        });

        att_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Login", "Logout" }));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Attendance type");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Points");

        pts_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pts_addActionPerformed(evt);
            }
        });

        btn_enter.setText("ENTER");
        btn_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enterActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Info");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Delete record");

        att_delete_record.setText("type log_id to delete");
        att_delete_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                att_delete_recordMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                att_delete_recordMouseExited(evt);
            }
        });

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(text_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(text_points, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(text_status, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(text_idnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(att_type, 0, 151, Short.MAX_VALUE)
                                .addComponent(text_addinfo)
                                .addComponent(pts_add)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(btn_findacc, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btn_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(att_delete_record)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                                .addGap(24, 24, 24)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(date_find, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date_find))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_enter)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(att_delete_record, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_delete)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(text_idnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(text_username))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(text_points))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(text_status))
                        .addGap(35, 35, 35)
                        .addComponent(btn_findacc)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(att_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(text_addinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pts_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Logged in as:");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("id:");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("username:");

        id_log_id3.setForeground(new java.awt.Color(255, 255, 255));
        id_log_id3.setText("wwww");

        id_log_user3.setForeground(new java.awt.Color(255, 255, 255));
        id_log_user3.setText("wwww");

        time_text3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        time_text3.setForeground(new java.awt.Color(255, 255, 255));
        time_text3.setText("jLabel4");

        date_text3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        date_text3.setForeground(new java.awt.Color(255, 255, 255));
        date_text3.setText("jLabel4");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id_log_id3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id_log_user3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(date_text3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(time_text3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(id_log_id3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(id_log_user3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(time_text3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(date_text3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enterActionPerformed
        att_take();
        find_acc();
        att_update();
        
        text_addinfo.setText("");
        pts_add.setText("");
        JOptionPane.showMessageDialog(this, "Successful", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_enterActionPerformed

    private void btn_findaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findaccActionPerformed
        find_acc();
    }//GEN-LAST:event_btn_findaccActionPerformed

    private void date_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_findActionPerformed
        att_form();
        jTextField1.setText("type the date");
    }//GEN-LAST:event_date_findActionPerformed

    private void pts_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pts_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pts_addActionPerformed

    private void text_idnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_idnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_idnumberActionPerformed

    private void text_idnumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_idnumberKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_text_idnumberKeyTyped

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        del_att_record();
        att_delete_record.setText("type log_id to delete");
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void att_delete_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_att_delete_recordMouseClicked
        att_delete_record.setText("");
    }//GEN-LAST:event_att_delete_recordMouseClicked

    private void jTextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseExited
        
    }//GEN-LAST:event_jTextField1MouseExited

    private void att_delete_recordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_att_delete_recordMouseExited
        
    }//GEN-LAST:event_att_delete_recordMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(attendance_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(attendance_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(attendance_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(attendance_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new attendance_form().setVisible(true);
            }
        });
    }

    
    
    
    void del_att_record(){
        try {
            DBconnection.init();
            Connection c = DBconnection.getConnection();
            PreparedStatement ps = c.prepareStatement(
                    "delete from shatdb.attendance where idattendance ='"+ att_delete_record.getText() +"';"
                            
            );

            ps.execute();
            //JOptionPane.showMessageDialog(this, "Data Registered", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);

               att_update();
               log_delete();
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(this, "Successful", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);
            Logger.getLogger(addmember_form.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }
    
    void find_acc(){
        try {
            DBconnection.init();
            Connection c = DBconnection.getConnection();
            PreparedStatement ps = c.prepareStatement(
                "SELECT * FROM shatdb.acc_data where idacc_data=" + text_idnumber.getText() + ";");

            ResultSet rs = ps.executeQuery();
            //JOptionPane.showMessageDialog(this, "Data Registered", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);

            while (rs.next()) {
                text_idnumber.setText(rs.getString("idacc_data"));
                text_username.setText(rs.getString("username"));
                text_points.setText(rs.getString("points"));
                text_status.setText(rs.getString("ptstats"));

            }
            //log();
            att_update();
        } catch (SQLException ex) {
            Logger.getLogger(addmember_form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    
    
    
    
    
    void att_take() {
        try {
            DBconnection.init();
            Connection c = DBconnection.getConnection();
            PreparedStatement ps = c.prepareStatement(
                    "insert into shatdb.attendance(acc_data_idacc_data, att_date, att_time, att_description)values('"
                    + text_idnumber.getText() + "','"
                    + date_text3.getText() + "','"
                    + time_text3.getText() + "','"
                    + att_type.getSelectedItem()
                    + " // "+text_addinfo.getText()+"');"
            );

            ps.execute();
            //JOptionPane.showMessageDialog(this, "Data Registered", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);

            
            add_points();
            log();
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(this, "Successful", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);
            Logger.getLogger(addmember_form.class.getName()).log(Level.SEVERE, null, ex);
            
        }

    }

    
    void add_points(){
        
        int pts1 = Integer.parseInt(text_points.getText());
        int pts2 = Integer.parseInt(pts_add.getText());
        int ptsf = pts1 + pts2;
        
        try {
            DBconnection.init();
            Connection c = DBconnection.getConnection();
            PreparedStatement ps = c.prepareStatement(
                    "UPDATE shatdb.acc_data SET points = "+ptsf+" WHERE idacc_data = "+text_idnumber.getText()+";"
            );

            ps.execute();
            //JOptionPane.showMessageDialog(this, "Data Registered", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);

            
            log();
        } catch (SQLException ex) {
            Logger.getLogger(addmember_form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    
    void log() {

        try {
            DBconnection.init();
            Connection c = DBconnection.getConnection();
            PreparedStatement ps = c.prepareStatement("insert into shatdb.log(date_time, description, action_maker)values('"+formatted_dt+"', '"+att_type.getSelectedItem()+" att of "+text_username.getText()+"', '"+id_log_user3.getText()+"');");
            ps.execute();
            //JOptionPane.showMessageDialog(this, "Data Registered", "JDB Co.", JOptionPane.INFORMATION_MESSAGE);

            

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void log_delete() {

        try {
            DBconnection.init();
            Connection c = DBconnection.getConnection();
            PreparedStatement ps = c.prepareStatement("insert into shatdb.log(date_time, description, action_maker)values('"+formatted_dt+"', 'deleted att entry of "+text_username.getText()+"', '"+id_log_user3.getText()+"');");
            ps.execute();
            //JOptionPane.showMessageDialog(this, "Data Registered", "JDB Co.", JOptionPane.INFORMATION_MESSAGE);

            

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    void att_update() {
        try {
            DBconnection.init();
            Connection c = DBconnection.getConnection();
            PreparedStatement ps = c.prepareStatement(
                    "SELECT * FROM shatdb.attendance where acc_data_idacc_data='" + text_idnumber.getText()+"';");

            ResultSet rs = ps.executeQuery();
            //JOptionPane.showMessageDialog(this, "Data Registered", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);
            Table.setRowCount(0);
            while (rs.next()) {
                Table.addRow(new Object[]{rs.getString(1),rs.getString(3), rs.getString(4), rs.getString(5)});

            }
            //log();
        } catch (SQLException ex) {
            Logger.getLogger(addmember_form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    
    
    
    void att_form() {
        try {
            DBconnection.init();
            Connection c = DBconnection.getConnection();
            PreparedStatement ps = c.prepareStatement(
                    "SELECT * FROM shatdb.attendance where acc_data_idacc_data='" + text_idnumber.getText() +"' and att_date = '"+ jTextField1.getText()+"';");

            ResultSet rs = ps.executeQuery();
            //JOptionPane.showMessageDialog(this, "Data Registered", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);
            Table.setRowCount(0);
            while (rs.next()) {
                Table.addRow(new Object[]{rs.getString(1),rs.getString(3), rs.getString(4), rs.getString(5)});

            }
            //log();
        } catch (SQLException ex) {
            Logger.getLogger(addmember_form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void clock() {
        Thread clock = new Thread() {
            public void run() {
                try {
                    while (true) {
                        Calendar cal = new GregorianCalendar();
                        int day = cal.get(Calendar.DAY_OF_MONTH);
                        int month = cal.get(Calendar.MONTH) + 1;
                        int year = cal.get(Calendar.YEAR);
                        int second = cal.get(Calendar.SECOND);
                        int minute = cal.get(Calendar.MINUTE);
                        int hour = cal.get(Calendar.HOUR);

                        time_text3.setText(hour + ":" + minute + ":" + second);
                        date_text3.setText(day + "-" + month + "-" + year);
                        //  getTime=lbltime.getText();
                        // getDate=lbldate.getText();
                        sleep(1000);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e);

                }
            }
        };
        clock.start();
    }

    void set_id_log_string(String id, String username) {
        id_log_id3.setText(id);
        id_log_user3.setText(username);

    }

    
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField att_delete_record;
    private javax.swing.JComboBox<String> att_type;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_enter;
    private javax.swing.JButton btn_findacc;
    private javax.swing.JButton date_find;
    private javax.swing.JLabel date_text3;
    private javax.swing.JLabel id_log_id3;
    private javax.swing.JLabel id_log_user3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField pts_add;
    private javax.swing.JTextField text_addinfo;
    private javax.swing.JTextField text_idnumber;
    private javax.swing.JLabel text_points;
    private javax.swing.JLabel text_status;
    private javax.swing.JLabel text_username;
    private javax.swing.JLabel time_text3;
    // End of variables declaration//GEN-END:variables
}
