/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shsdc_shat_mms;

import java.time.LocalDateTime;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author panal
 */
public class Login extends javax.swing.JFrame {

    LocalDateTime dt_now = LocalDateTime.now();
    DateTimeFormatter dt_now_new = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
    String formatted_dt = dt_now.format(dt_now_new);
    
    
    
        String db_username;
        String db_password;
        String db_accrank;
        String db_idacc_data;
        
    public admin_menu amenu;
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        org_logo = new javax.swing.JLabel();
        org_name_head = new javax.swing.JLabel();
        login_button = new javax.swing.JButton();
        label_username = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();
        uname_field = new javax.swing.JTextField();
        pword_field = new javax.swing.JPasswordField();
        panel2 = new javax.swing.JPanel();
        forGIF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SH-AT MMS LOGIN");
        setName("Login_frame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(640, 360));

        panel1.setBackground(new java.awt.Color(51, 51, 51));

        org_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource_pics/rsz_redrawed_logo_senior_high_action_team.png"))); // NOI18N

        org_name_head.setBackground(new java.awt.Color(255, 255, 255));
        org_name_head.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        org_name_head.setForeground(new java.awt.Color(255, 255, 255));
        org_name_head.setText("<html> <p align=\"center\"> SENIOR HIGH <br>ACTION TEAM </p> </html>");

        login_button.setText("LOGIN");
        login_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        login_button.setRolloverEnabled(true);
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        login_button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_buttonKeyPressed(evt);
                enter(evt);
            }
        });

        label_username.setForeground(new java.awt.Color(255, 255, 255));
        label_username.setText("Username");

        label_password.setForeground(new java.awt.Color(255, 255, 255));
        label_password.setText("Password");

        uname_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uname_fieldActionPerformed(evt);
            }
        });

        pword_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pword_fieldActionPerformed(evt);
            }
        });
        pword_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pword_fieldKeyPressed(evt);
            }
        });

        forGIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource_pics/rsz_shat_poster.png"))); // NOI18N

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(forGIF, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(forGIF, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(label_password, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pword_field))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(label_username, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(uname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(org_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(org_name_head, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(org_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(org_name_head, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uname_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pword_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(login_button)
                .addGap(116, 116, 116))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void uname_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uname_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uname_fieldActionPerformed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        Login_check();
    }//GEN-LAST:event_login_buttonActionPerformed

    private void login_buttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_buttonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("Hello");
            
        }
    }//GEN-LAST:event_login_buttonKeyPressed

    private void enter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("Hello");
        }
    }//GEN-LAST:event_enter

    private void pword_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pword_fieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pword_fieldActionPerformed

    private void pword_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pword_fieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("login by enter key pressed in pword field");
            Login_check();
        }
    }//GEN-LAST:event_pword_fieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    void Login_check() {

        String username = uname_field.getText();
        String password = pword_field.getText();
        
        String acc_admin = "admin";
        String acc_member = "member";
        Boolean login_status = false;

        try {
            DBconnection.init();
            Connection c = DBconnection.getConnection();
            PreparedStatement ps = c.prepareStatement("select idacc_data, acc_rank, username, password from shatdb.acc_data where username='" + username + "'");
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                db_idacc_data = rs.getString("idacc_data");
                
                db_accrank = rs.getString("acc_rank");

                db_username = rs.getString("username");

                db_password = rs.getString("password");

                System.out.println("Logging in " + db_username + "   " + db_password);
                if (username.equals(db_username) && password.equals(db_password) && acc_admin.equals(db_accrank)) {
                    JOptionPane.showMessageDialog(this, "Login Success", "SH-AT MMS", JOptionPane.INFORMATION_MESSAGE);
                    setVisible(false);
                    admin_menu amenu = new admin_menu();
                    
                    amenu.set_id_log_string(db_idacc_data, db_username);
                    
                    amenu.setVisible(true);
                    amenu.setResizable(false);
                    login_status = true;
                    
                    
                    
                    log();
                } else if (username.equals(db_username) && password.equals(db_password) && acc_member.equals(db_accrank)) {
                    JOptionPane.showMessageDialog(this, "Login Success", "SH-AT MMS", JOptionPane.INFORMATION_MESSAGE);
                    setVisible(false);
                    member_menu mmenu = new member_menu();
                    
                    mmenu.set_id_log_string(db_idacc_data, db_username);
                    
                    mmenu.setVisible(true);
                    mmenu.setResizable(false);
                    login_status = true;
                    log();
                } else {
                    login_status = false;
                    //System.out.println("login failed");
                    //JOptionPane.showMessageDialog(this, "Wrong Username/Password", "SH-AT MMS", JOptionPane.INFORMATION_MESSAGE);
                    break;
                }

            }
            
            if (login_status == false) {
                if (!rs.next()) {
                    System.out.println("no data");
                    JOptionPane.showMessageDialog(this, "invalid credentials", "SH-AT MMS", JOptionPane.INFORMATION_MESSAGE);

                }
            }

            uname_field.setText("");
            pword_field.setText("");
            uname_field.requestFocus();
            //JOptionPane.showMessageDialog(this, "invalid credentials", "SH-AT MMS", JOptionPane.INFORMATION_MESSAGE);
            
            //JOptionPane.showMessageDialog(this, "Login Success", "SH-AT MMS", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void log() {

        try {
            DBconnection.init();
            Connection c = DBconnection.getConnection();
            PreparedStatement ps = c.prepareStatement("insert into shatdb.log(date_time, description, action_maker)values('"+formatted_dt+"', 'log in', '"+db_username+"');");
            ps.execute();
            //JOptionPane.showMessageDialog(this, "Data Registered", "JDB Co.", JOptionPane.INFORMATION_MESSAGE);

            

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel forGIF;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_username;
    private javax.swing.JButton login_button;
    private javax.swing.JLabel org_logo;
    private javax.swing.JLabel org_name_head;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPasswordField pword_field;
    private javax.swing.JTextField uname_field;
    // End of variables declaration//GEN-END:variables
}
