/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shsdc_shat_mms;

import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author panal
 */
public class memberprofile_form extends javax.swing.JFrame {

    LocalDateTime dt_now = LocalDateTime.now();
    DateTimeFormatter dt_now_new = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
    String formatted_dt = dt_now.format(dt_now_new);
    DefaultTableModel Table = new DefaultTableModel();

    /**
     * Creates new form memberprofile_form
     */
    public memberprofile_form() {
        initComponents();
        //Table = (DefaultTableModel) jTable1.getModel();
        clock();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        id_log_id3 = new javax.swing.JLabel();
        id_log_user3 = new javax.swing.JLabel();
        time_text3 = new javax.swing.JLabel();
        date_text3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text_accrank = new javax.swing.JLabel();
        text_username = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        text_fname = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        text_lname = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        text_company = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        text_batch = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        text_rank = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        text_designation = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        text_points = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        text_status = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        text_schoolyearl = new javax.swing.JLabel();
        btn_find_acc = new javax.swing.JButton();
        text_idnumber = new javax.swing.JTextField();
        org_logo = new javax.swing.JLabel();
        org_name_head = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        text_password = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        u_company = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        u_rank = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        u_designation = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        u_status = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        u_sc_year = new javax.swing.JComboBox<>();
        org_name_head1 = new javax.swing.JLabel();
        btn_update_password = new javax.swing.JButton();
        btn_update_info = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        u_fname = new javax.swing.JTextField();
        u_lname = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        insignia_slot = new javax.swing.JLabel();
        btn_add_points = new javax.swing.JButton();
        u_add_pts = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Member Profile");
        setResizable(false);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Logged in as:");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("id:");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("username:");

        id_log_id3.setForeground(new java.awt.Color(255, 255, 255));
        id_log_id3.setText("wwww");

        id_log_user3.setForeground(new java.awt.Color(255, 255, 255));
        id_log_user3.setText("wwww");

        time_text3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        time_text3.setForeground(new java.awt.Color(255, 255, 255));
        time_text3.setText("jLabel4");

        date_text3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        date_text3.setForeground(new java.awt.Color(255, 255, 255));
        date_text3.setText("jLabel4");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id_log_id3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id_log_user3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(date_text3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(time_text3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(id_log_id3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(id_log_user3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(time_text3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(date_text3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("id number");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("account rank");

        text_accrank.setForeground(new java.awt.Color(255, 255, 255));
        text_accrank.setText("text_accrank");

        text_username.setForeground(new java.awt.Color(255, 255, 255));
        text_username.setText("text_username");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("username");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("first name");

        text_fname.setForeground(new java.awt.Color(255, 255, 255));
        text_fname.setText("text_fname");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("last name");

        text_lname.setForeground(new java.awt.Color(255, 255, 255));
        text_lname.setText("text_lname");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("company");

        text_company.setForeground(new java.awt.Color(255, 255, 255));
        text_company.setText("text_company");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("batch");

        text_batch.setForeground(new java.awt.Color(255, 255, 255));
        text_batch.setText("text_batch");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("rank");

        text_rank.setForeground(new java.awt.Color(255, 255, 255));
        text_rank.setText("text_rank");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("designation");

        text_designation.setForeground(new java.awt.Color(255, 255, 255));
        text_designation.setText("text_designation");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("POINTS");

        text_points.setForeground(new java.awt.Color(255, 255, 255));
        text_points.setText("text_points");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("status");

        text_status.setForeground(new java.awt.Color(255, 255, 255));
        text_status.setText("text_status");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("School Year");

        text_schoolyearl.setForeground(new java.awt.Color(255, 255, 255));
        text_schoolyearl.setText("text_schoolyear");

        btn_find_acc.setText("FIND ACCOUNT");
        btn_find_acc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_find_accActionPerformed(evt);
            }
        });

        text_idnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_idnumberActionPerformed(evt);
            }
        });
        text_idnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_idnumberKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_idnumberKeyTyped(evt);
            }
        });

        org_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource_pics/rsz_redrawed_logo_senior_high_action_team.png"))); // NOI18N

        org_name_head.setBackground(new java.awt.Color(255, 255, 255));
        org_name_head.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        org_name_head.setForeground(new java.awt.Color(255, 255, 255));
        org_name_head.setText("<html> <p align=\"center\"> SENIOR HIGH ACTION TEAM<br> ADMIN MENU || PROFILES   </p> </html>");

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("password");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("company");

        u_company.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "staff", "alpha", "bravo", "charlie", "delta" }));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("rank");

        u_rank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "colonel", "lt. colonel", "major", "captain", "1st lieutenant", "2nd lieutenant", "officer candidate", "1 AT", "2 AT", "3 AT", "4 AT", "aspirant" }));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("designation");

        u_designation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "corps commander", "staff/Executive", "staff/Administrative", "staff/Liaison", "staff/Logistics", "staff/Safety", "staff/Intelligence", "staff/Information", "company commander", "company executive", "company guidon", "color commander", "color flag bearer", "color guard", "platoon leader", "seargent", "element" }));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("status");

        u_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "active", "inactive", "removed", "alumni" }));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("School Year");

        u_sc_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "2017-2018", "2018-2019", "2019-2020", "2020-2021", "2021-2022", "2022-2023", "2023-2024", "2024-2025" }));
        u_sc_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_sc_yearActionPerformed(evt);
            }
        });

        org_name_head1.setBackground(new java.awt.Color(255, 255, 255));
        org_name_head1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        org_name_head1.setForeground(new java.awt.Color(255, 255, 255));
        org_name_head1.setText("INFO UPDATE");

        btn_update_password.setText("UPDATE PASSWORD");
        btn_update_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_passwordActionPerformed(evt);
            }
        });

        btn_update_info.setText("UPDATE INFO");
        btn_update_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_infoActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("first name");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("last name");

        u_fname.setText("none");
        u_fname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                u_fnameMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                u_fnameMouseExited(evt);
            }
        });

        u_lname.setText("none");
        u_lname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                u_lnameMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                u_lnameMouseExited(evt);
            }
        });
        u_lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                u_lnameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(org_name_head1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_update_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(155, 155, 155))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(btn_update_info, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(u_sc_year, 0, 221, Short.MAX_VALUE)
                            .addComponent(u_status, 0, 221, Short.MAX_VALUE)
                            .addComponent(u_designation, 0, 221, Short.MAX_VALUE)
                            .addComponent(u_rank, 0, 221, Short.MAX_VALUE)
                            .addComponent(u_company, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(u_fname)
                            .addComponent(u_lname))))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(text_password, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(org_name_head1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btn_update_password)
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_company, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_rank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(u_sc_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btn_update_info)
                .addGap(42, 42, 42))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(text_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addContainerGap(440, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insignia_slot, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insignia_slot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_add_points.setText("ADD POINTS");
        btn_add_points.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_pointsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(org_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(org_name_head, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addComponent(jLabel14)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10)
                                .addComponent(jLabel20)
                                .addComponent(jLabel12)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(text_schoolyearl, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(text_accrank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(text_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(text_batch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(text_rank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(text_designation, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(text_points, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(text_company, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(text_lname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(text_fname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(text_idnumber))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(u_add_pts))
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_find_acc, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_add_points, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(org_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(org_name_head, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(text_accrank)
                                .addGap(16, 16, 16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(text_idnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(text_username))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(text_fname))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(text_lname))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(text_company)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_batch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(text_rank))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(text_designation))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(text_status))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_schoolyearl)
                    .addComponent(jLabel12))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_points)
                    .addComponent(jLabel4)
                    .addComponent(u_add_pts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_find_acc)
                    .addComponent(btn_add_points))
                .addGap(11, 11, 11))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_find_accActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_find_accActionPerformed
        find_acc();
        jlabel_insignia();
    }//GEN-LAST:event_btn_find_accActionPerformed

    private void btn_update_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_passwordActionPerformed
        update_password();
    }//GEN-LAST:event_btn_update_passwordActionPerformed

    private void u_sc_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_sc_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_sc_yearActionPerformed

    private void btn_update_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_infoActionPerformed
        update_info();
        
    }//GEN-LAST:event_btn_update_infoActionPerformed

    private void u_fnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u_fnameMouseClicked
        u_fname.setText("");
    }//GEN-LAST:event_u_fnameMouseClicked

    private void u_lnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u_lnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_lnameKeyPressed

    private void u_lnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u_lnameMouseClicked
        u_lname.setText("");
    }//GEN-LAST:event_u_lnameMouseClicked

    private void u_fnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u_fnameMouseExited
        u_fname.setText("none");

    }//GEN-LAST:event_u_fnameMouseExited

    private void u_lnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u_lnameMouseExited
        u_lname.setText("none");
    }//GEN-LAST:event_u_lnameMouseExited

    private void btn_add_pointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_pointsActionPerformed
        add_points();
        u_add_pts.setText("");
    }//GEN-LAST:event_btn_add_pointsActionPerformed

    private void text_idnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_idnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_idnumberActionPerformed

    private void text_idnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_idnumberKeyPressed
        
    }//GEN-LAST:event_text_idnumberKeyPressed

    private void text_idnumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_idnumberKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_text_idnumberKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(memberprofile_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(memberprofile_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(memberprofile_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(memberprofile_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new memberprofile_form().setVisible(true);
                
            }
        });
    }

    
    
    
    
    
    
    void log_update() {

        try {
            DBconnection.init();
            Connection c = DBconnection.getConnection();
            PreparedStatement ps = c.prepareStatement("insert into shatdb.log(date_time, description, action_maker)values('"+formatted_dt+"', 'Info update for "+text_username.getText()+"', '"+id_log_user3.getText()+"');");
            ps.execute();
            //JOptionPane.showMessageDialog(this, "Data Registered", "JDB Co.", JOptionPane.INFORMATION_MESSAGE);

            

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void log_addpts() {

        try {
            DBconnection.init();
            Connection c = DBconnection.getConnection();
            PreparedStatement ps = c.prepareStatement("insert into shatdb.log(date_time, description, action_maker)values('"+formatted_dt+"', '"+u_add_pts.getText()+" points added to "+text_username.getText()+"', '"+id_log_user3.getText()+"');");
            ps.execute();
            //JOptionPane.showMessageDialog(this, "Data Registered", "JDB Co.", JOptionPane.INFORMATION_MESSAGE);

            

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void add_points(){
        int pts1 = Integer.parseInt(text_points.getText());
        int pts2 = Integer.parseInt(u_add_pts.getText());
        int ptsf = pts1 + pts2;
        
        try {
            DBconnection.init();
            Connection c = DBconnection.getConnection();
            PreparedStatement ps = c.prepareStatement(
                    "UPDATE shatdb.acc_data SET points = "+ptsf+" WHERE idacc_data = "+text_idnumber.getText()+";"
            );

            ps.execute();
            JOptionPane.showMessageDialog(this, "Points added!!", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);

            find_acc();
            log_addpts();
        } catch (SQLException ex) {
            Logger.getLogger(addmember_form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void jlabel_insignia() {
        String curr_rank = text_rank.getText();
        /*colonel
        lt. colonel
        major
        captain
        1st lieutenant
        2nd lieutenant
        officer candidate
        1 AT
        2 AT
        3 AT
        4 AT
        aspirant*/
        if (curr_rank.equals("colonel")) {
            insignia_slot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insignia/colonel.png")));
        }
        if (curr_rank.equals("lt. colonel")) {
            insignia_slot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insignia/lt. colonel.png")));
        }
        if (curr_rank.equals("major")) {
            insignia_slot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insignia/major.png")));
        }
        if (curr_rank.equals("captain")) {
            insignia_slot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insignia/captain.png")));
        }
        if (curr_rank.equals("1st lieutenant")) {
            insignia_slot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insignia/1st lieutenant.png")));
        }
        if (curr_rank.equals("2nd lieutenant")) {
            insignia_slot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insignia/2nd lieutenant.png")));
        }
        if (curr_rank.equals("officer candidate")) {
            insignia_slot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insignia/1 AT.png")));
        }
        if (curr_rank.equals("1 AT")) {
            insignia_slot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insignia/1 AT.png")));
        }
        if (curr_rank.equals("2 AT")) {
            insignia_slot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insignia/2 AT.png")));
        }
        if (curr_rank.equals("3 AT")) {
            insignia_slot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insignia/3 AT.png")));
        }
        if (curr_rank.equals("4 AT")) {
            insignia_slot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insignia/4 AT.png")));
        }
    }

    void update_info() {
        String non = "none";
        String cu_fname = u_fname.getText();
        String cu_lname = u_lname.getText();
        String cu_company = (String) u_company.getSelectedItem();
        String cu_rank = (String) u_rank.getSelectedItem();
        String cu_designation = (String) u_designation.getSelectedItem();
        String cu_status = (String) u_status.getSelectedItem();
        String cu_sc_year = (String) u_sc_year.getSelectedItem();

        if (cu_fname.equals(non)) {
            System.out.println("info=none");
        } else {
            try {
                DBconnection.init();
                Connection c = DBconnection.getConnection();
                PreparedStatement ps = c.prepareStatement(
                        "update shatdb.acc_data set fname = '" + u_fname.getText() + "' where idacc_data ='" + text_idnumber.getText() + "';"
                );

                ps.execute();

                text_password.setText("");

            } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(this, "Successful", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);
                Logger.getLogger(addmember_form.class.getName()).log(Level.SEVERE, null, ex);

            }
        }

        if (cu_lname.equals(non)) {
            System.out.println("info=none");
        } else {
            try {
                DBconnection.init();
                Connection c = DBconnection.getConnection();
                PreparedStatement ps = c.prepareStatement(
                        "update shatdb.acc_data set lname = '" + u_lname.getText() + "' where idacc_data ='" + text_idnumber.getText() + "';"
                );

                ps.execute();

                text_password.setText("");

            } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(this, "Successful", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);
                Logger.getLogger(addmember_form.class.getName()).log(Level.SEVERE, null, ex);

            }
        }

        if (cu_company.equals(non)) {
            System.out.println("info=none");
        } else {
            try {
                DBconnection.init();
                Connection c = DBconnection.getConnection();
                PreparedStatement ps = c.prepareStatement(
                        "update shatdb.acc_data set company = '" + u_company.getSelectedItem() + "' where idacc_data ='" + text_idnumber.getText() + "';"
                );

                ps.execute();

                text_password.setText("");

            } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(this, "Successful", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);
                Logger.getLogger(addmember_form.class.getName()).log(Level.SEVERE, null, ex);

            }
        }

        if (cu_rank.equals(non)) {
            System.out.println("info=none");
        } else {
            try {
                DBconnection.init();
                Connection c = DBconnection.getConnection();
                PreparedStatement ps = c.prepareStatement(
                        "update shatdb.acc_data set corps_rank = '" + u_rank.getSelectedItem() + "' where idacc_data ='" + text_idnumber.getText() + "';"
                );

                ps.execute();

                text_password.setText("");

            } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(this, "Successful", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);
                Logger.getLogger(addmember_form.class.getName()).log(Level.SEVERE, null, ex);

            }
        }

        if (cu_designation.equals(non)) {
            System.out.println("info=none");
        } else {
            try {
                DBconnection.init();
                Connection c = DBconnection.getConnection();
                PreparedStatement ps = c.prepareStatement(
                        "update shatdb.acc_data set designation = '" + u_designation.getSelectedItem() + "' where idacc_data ='" + text_idnumber.getText() + "';"
                );

                ps.execute();

                text_password.setText("");

            } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(this, "Successful", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);
                Logger.getLogger(addmember_form.class.getName()).log(Level.SEVERE, null, ex);

            }
        }

        if (cu_status.equals(non)) {
            System.out.println("info=none");
        } else {
            try {
                DBconnection.init();
                Connection c = DBconnection.getConnection();
                PreparedStatement ps = c.prepareStatement(
                        "update shatdb.acc_data set ptstats = '" + u_status.getSelectedItem() + "' where idacc_data ='" + text_idnumber.getText() + "';"
                );

                ps.execute();

                text_password.setText("");

            } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(this, "Successful", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);
                Logger.getLogger(addmember_form.class.getName()).log(Level.SEVERE, null, ex);

            }
        }

        if (cu_sc_year.equals(non)) {
            System.out.println("info=none");
        } else {
            try {
                DBconnection.init();
                Connection c = DBconnection.getConnection();
                PreparedStatement ps = c.prepareStatement(
                        "update shatdb.acc_data set school_year_idschool_year = '" + u_sc_year.getSelectedItem() + "' where idacc_data ='" + text_idnumber.getText() + "';"
                );

                ps.execute();

                text_password.setText("");

            } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(this, "Successful", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);
                Logger.getLogger(addmember_form.class.getName()).log(Level.SEVERE, null, ex);

            }
        }

        if (cu_fname.equals(non) && cu_lname.equals(non) && cu_company.equals(non) && cu_rank.equals(non) && cu_designation.equals(non) && cu_sc_year.equals(non) && cu_status.equals(non)) {
            JOptionPane.showMessageDialog(this, "no information to be updated!!", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "INFO updated!!", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);
        }

        u_fname.setText(non);
        u_lname.setText(non);
        u_company.setSelectedItem("none");
        u_rank.setSelectedItem("none");
        u_designation.setSelectedItem("none");
        u_sc_year.setSelectedItem("none");
        u_status.setSelectedItem("none");
        jlabel_insignia();
        find_acc();
        log_update();

    }

    void update_password() {
        try {
            DBconnection.init();
            Connection c = DBconnection.getConnection();
            PreparedStatement ps = c.prepareStatement(
                    "update shatdb.acc_data set password = '" + text_password.getText() + "' where idacc_data ='" + text_idnumber.getText() + "';"
            );

            ps.execute();
            JOptionPane.showMessageDialog(this, "Password updated!!", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);
            text_password.setText("");

        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(this, "Successful", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);
            Logger.getLogger(addmember_form.class.getName()).log(Level.SEVERE, null, ex);

        }
    }

    void find_acc() {

        try {
            DBconnection.init();
            Connection c = DBconnection.getConnection();
            PreparedStatement ps = c.prepareStatement(
                    "SELECT * FROM shatdb.acc_data where idacc_data=" + text_idnumber.getText() + ";");

            ResultSet rs = ps.executeQuery();
            //JOptionPane.showMessageDialog(this, "Data Registered", "Senior High Action Team Database", JOptionPane.INFORMATION_MESSAGE);

            while (rs.next()) {

                text_idnumber.setText(rs.getString("idacc_data"));
                text_accrank.setText(rs.getString("acc_rank"));
                text_username.setText(rs.getString("username"));
                //password.setText(rs.getString("idacc_data"));
                text_fname.setText(rs.getString("fname"));
                text_lname.setText(rs.getString("lname"));
                text_company.setText(rs.getString("company"));
                text_batch.setText(rs.getString("batch"));
                text_rank.setText(rs.getString("corps_rank"));
                text_designation.setText(rs.getString("designation"));
                text_points.setText(rs.getString("points"));
                text_status.setText(rs.getString("ptstats"));
                text_schoolyearl.setText(rs.getString("school_year_idschool_year"));
            }
            jlabel_insignia();
            //log();
        } catch (SQLException ex) {
            Logger.getLogger(addmember_form.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void clock() {
        Thread clock = new Thread() {
            public void run() {
                try {
                    while (true) {
                        Calendar cal = new GregorianCalendar();
                        int day = cal.get(Calendar.DAY_OF_MONTH);
                        int month = cal.get(Calendar.MONTH) + 1;
                        int year = cal.get(Calendar.YEAR);
                        int second = cal.get(Calendar.SECOND);
                        int minute = cal.get(Calendar.MINUTE);
                        int hour = cal.get(Calendar.HOUR);

                        time_text3.setText(hour + ":" + minute + ":" + second);
                        date_text3.setText(day + "-" + month + "-" + year);
                        //  getTime=lbltime.getText();
                        // getDate=lbldate.getText();
                        sleep(1000);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e);

                }
            }
        };
        clock.start();
    }

    void set_id_log_string(String id, String username) {
        id_log_id3.setText(id);
        id_log_user3.setText(username);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_points;
    private javax.swing.JButton btn_find_acc;
    private javax.swing.JButton btn_update_info;
    private javax.swing.JButton btn_update_password;
    private javax.swing.JLabel date_text3;
    private javax.swing.JLabel id_log_id3;
    private javax.swing.JLabel id_log_user3;
    private javax.swing.JLabel insignia_slot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel org_logo;
    private javax.swing.JLabel org_name_head;
    private javax.swing.JLabel org_name_head1;
    private javax.swing.JLabel text_accrank;
    private javax.swing.JLabel text_batch;
    private javax.swing.JLabel text_company;
    private javax.swing.JLabel text_designation;
    private javax.swing.JLabel text_fname;
    private javax.swing.JTextField text_idnumber;
    private javax.swing.JLabel text_lname;
    private javax.swing.JTextField text_password;
    private javax.swing.JLabel text_points;
    private javax.swing.JLabel text_rank;
    private javax.swing.JLabel text_schoolyearl;
    private javax.swing.JLabel text_status;
    private javax.swing.JLabel text_username;
    private javax.swing.JLabel time_text3;
    private javax.swing.JTextField u_add_pts;
    private javax.swing.JComboBox<String> u_company;
    private javax.swing.JComboBox<String> u_designation;
    private javax.swing.JTextField u_fname;
    private javax.swing.JTextField u_lname;
    private javax.swing.JComboBox<String> u_rank;
    private javax.swing.JComboBox<String> u_sc_year;
    private javax.swing.JComboBox<String> u_status;
    // End of variables declaration//GEN-END:variables
}
